### PR TITLE
Enemy class formatting

### PR DESCRIPTION
**Pull request by FlameHorizon**
Hey. I've started working on improving code in the `Enemy.cs` class. Because I haven't found any coding conventions which this projects suppose to follow, I applied mine which I closely follows (but not exactly) [Microsoft’s convention](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions).

Idea is that it's better have any convention and follow it rather than making mess in the code.

PS. I still see few places where code can be improve.

- [ ] `public override ushort TotalStat(Kernel_bin.Stat s)` - change argument name

- [ ] `public int EXPExtra(byte lasthitlevel)` - update argument casing

### CODE REVIEW

**Comment by Sebanisu** [comment]
I have done this on my fork. I have been dragging my feet. I should probably commit to master. though I haven't tested it thoroughly.

**Comment by FlameHorizon** [comment]
Thanks for the info. I looked at your fork and it looks promising. What do you think, should I wait for you changes to be applied into master?

I guess it makes this PR irrelevant.

**Comment by Sebanisu** [comment]
I will try to get it merged by Monday. I work weekends.

**Comment by FlameHorizon** [comment]
Cool @Sebanisu. Cheers!

**Pull request closed without merging**
